config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :sounds, only: [:new, :create, :edit, :update, :destroy, :index]
  resources :styles, only: [:new, :create, :edit, :update, :destroy, :index]
  resources :boxes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
  SIZES = [
    :extra_tiny,
    :tiny,
    :extra_small,
    :small,
    :extra_medium,
    :medium,
    :large,
    :extra_large,
    :huge,
    :extra_huge,
    :monumental,
    :extra_monumental
  ]
  validates :size, :name, presence: true
  belongs_to :user, optional: true
  belongs_to :sound
  belongs_to :style
  enum size: SIZES
end

app/models/sound.rb
class Sound < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :sound_file
  has_many :boxes, dependent: :destroy

  validates :sound_file, attached: true, content_type: ['audio/mpeg', 'audio/ogg', 'audio/aac'], size: { less_than: 1.megabytes , message: 'Should be under 1Mb' }
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :pattern
  has_many :boxes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_theme

  def set_theme
    if params[:theme].present?
      theme = params[:theme].to_sym
      cookies[:theme] = {
        value: theme,
        expires: 20.year
      }
      redirect_to(request.referrer || root_path)
    end
  end

  def animal_talk
  [
    "Moo.",
    "Moo!",
    "Moo moo.",
    "Moo moo!",
    "Mooooo.",
    "Mooooo!",
    "Meow.",
    "Meow!",
    "Baa.",
    "Baa!",
    "Baa baa.",
    "Baa baa!",
    "Oink.",
    "Oink!",
    "Oink oink.",
    "Oink oink!"
  ]
  .sample
end

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  def index
    @boxes = Box.all.order(created_at: 'DESC')
  end

  def show
  end

  def new
    @box = Box.new
  end

  def create
    @box = Box.new(box_params)
    if @box.save
      redirect_to boxes_path, notice: "Your MooBox #{@box.name} has been created! #{animal_talk}"
    else
      flash.alert = "We could not create this MooBox, please try again. #{animal_talk}"
      render :new
    end
  end

  def edit
  end

  def update
    if @box.update(box_params)
      redirect_to box_path(@box), notice: "Your MooBox #{@box.name} has been succesfully modified! #{animal_talk}"
    else
      flash.alert = "We are missing infos to modify your MooBox, please try again. #{animal_talk}"
      render :edit
    end
  end

  def destroy
    if @box.destroy
      redirect_to boxes_path, notice: "Your MooBox has been destroyed! #{animal_talk}"
    else
      flash.alert = "Your MooBox has not been destroyed! Please try again. #{animal_talk}"
    end
  end

  private

  def set_box
    @box = Box.find(params[:id])
  end

  def box_params
    params.require(:box).permit(:name, :size, :sound_id, :style_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: [:edit, :update, :destroy]

  def index
    @sounds = Sound.all.order(created_at: "DESC")
  end

  def new
    @sound = Sound.new
  end

  def create
    @sound = Sound.new(sound_params)
    if @sound.save
      redirect_to root_path, notice: "Sound \"#{@sound.name}\" is now available for new MooBoxes! #{animal_talk}"
    else
      flash.alert = "We couldn't create this sound, please try again. #{animal_talk}"
      render :new
    end
  end

  def edit
  end

  def update
    if @sound.update(sound_params)
      redirect_to root_path, notice: "Sound \"#{@sound.name}\" was modified! #{animal_talk}"
    else
      flash.alert = "We couldn't modify this sound, please try again. #{animal_talk}"
      render :edit
    end
  end

  def destroy
    name = @sound.name
    if @sound.destroy
      redirect_to sounds_path
      flash.notice = "Sound \"#{name}\" has been deleted! #{animal_talk}"
    else
      flash.alert = "Sound \"#{name}\" couldn't be deleted, please try again. #{animal_talk}"
    end
  end

  private

  def set_sound
    @sound = Sound.find(params[:id])
  end

  def sound_params
    params.require(:sound).permit(:name, :sound_file)
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:edit, :update, :destroy]

  def index
    @styles = Style.all.order(created_at: "DESC")
  end

  def new
    @style = Style.new
  end

  def create
    @style = Style.new(style_params)
    if @style.save
      redirect_to root_path, notice:
      flash.notice = "Style \"#{@style.name}\" is now available for new MooBoxes! #{animal_talk}"
    else
      flash.alert = "We couldn't create this style, please try again. #{animal_talk}"
      render :new
    end
  end

  def edit
  end

  def update
    if @style.update(style_params)
      redirect_to root_path, notice: "Style \"#{@style.name}\" was modified! #{animal_talk}"
    else
      flash.alert = "We couldn't modify this style, please try again. #{animal_talk}"
      render :edit
    end
  end

  def destroy
    name = @style.name
    if @style.destroy
      redirect_to styles_path
      flash.notice = "Style \"#{name}\" has been deleted! #{animal_talk}"
    else
      flash.alert = "Style \"#{name}\" couldn't be deleted, please try again. #{animal_talk}"
    end
  end

  private

  def set_style
    @style = Style.find(params[:id])
  end

  def style_params
    params.require(:style).permit(:name, :pattern)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def theme_is_dark?
    return false unless cookies[:theme].present?
    cookies[:theme] == 'dark'
  end

  def current_theme
    return 'light' unless cookies[:theme].present?
    cookies[:theme]
  end

  def current_opposite_theme
    current_theme == 'light' ? 'dark' : 'light'
  end

  def display_current_method(width)
    # cadre de 50 caracteres de large
    length = controller_name.length + action_name.length + 5
    side = "=" * ((width-length)/2)
    string = "#{side}#{" #{controller_name.upcase} - #{action_name.upcase} "}#{side}"
    string.length < 50 ? string + "=" : string
  end

end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/boxes/edit.html.erb
<h1>Boxes#edit</h1>
<p>Find me in app/views/boxes/edit.html.erb</p>

<%= simple_form_for @box do |f| %>
  <%= f.input :name, label: false, placeholder: 'Name' %>
  <%= f.input :size, prompt: 'Size', collection: Box::SIZES, label: false %>
  <%= f.association :style, prompt: 'Style', :label_method => lambda { |style| "#{style.name}" }, label: false %>
  <%= f.association :sound, prompt: 'Sound', :label_method => lambda { |sound| "#{sound.name}" }, label: false %>
  <%= f.submit "Apply changes" %>
<% end %>

app/views/boxes/index.html.erb
<h1>Boxes#index</h1>
<p>Find me in app/views/boxes/index.html.erb</p>

<ol>
  <% @boxes.each_with_index do |box, i| %>
    <li>
      <p><strong><%= box.name %></strong> | (<em><%= box.size %></em>) || <%= link_to "Edit dat shiet", edit_box_path(box) %> || <%= link_to "Delete dat shiet", box_path(box), method: :delete %> | style: <%= box.style.name %> | sound: <%= box.sound.name %> <%= render 'sounds/play_button', sound: box.sound, id: i %></p>
    </li>
    <hr>
  <% end %>
</ol>

app/views/boxes/new.html.erb
<div class="container-new-box">

  <h1 class="new_title">Let's create your Moobox!</h1>

  <div class="form-new">
    <%= simple_form_for @box do |f| %>
      <div class="form-inputs">
        <%= f.input :name, label: false, placeholder: 'Ex: Marguerite' %>
        <%= f.input :size, prompt: 'Size', collection: Box::SIZES, label: false %>
      </div>
      <div class="form-dropdown">
        <%= f.association :style, prompt: 'Style', :label_method => lambda { |style| "#{style.name}" }, label: false %>
        <%= f.association :sound, prompt: 'Sound', :label_method => lambda { |sound| "#{sound.name}" }, label: false %>
      </div>
      <div class="form-btn">
        <%= f.submit "Create Moobox! (moo)" %>
      </div>
    <% end %>
  </div>

</div>

app/views/boxes/show.html.erb
<h1>Boxes#show</h1>
<p>Find me in app/views/boxes/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Moobox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

  </head>

  <body class="<%= cookies[:theme] || 'light' %> <%= "sass-theme-#{(cookies[:theme] || 'light')}" %>" id="<%= controller_name %>-<%= action_name %>" >
    <!-- ================================================== -->
    <!-- <%= display_current_method(50) %> -->
    <!-- ================================================== -->

    <%= render 'shared/navbar' %>

    <%= yield %>

    <% flash.each do |type, msg| %>
      <div class="rails-flashes alert alert-<%= type == 'notice' ? 'success' : 'warning' %>">
        <%= msg %>
      </div>
    <% end %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

  </body>

</html>

app/views/pages/home.html.erb
<div class="container-home">
  <h1 class="main-title">Welcome to Moobox!</h1>

  <div class="features">

    <div class="features-info">
      <%= image_tag 'bear-2.svg', class: 'picto animal-picto' %>
      <h5 class="picto-txt" >Choose your animal</h5>
      <p class="picto-txt" >Choose among our selection of animals and pick your favorite!</p>
    </div>

    <div class="features-info">
      <%= image_tag 'bell-53.svg', class: 'picto bell-picto' %>
      <h5 class="picto-txt" >Choose your sound</h5>
      <p class="picto-txt" >Select the best sound for your animal</p>
    </div>

    <div class="features-info">
      <%= image_tag 'send-2.svg', class: 'picto send-picto' %>
      <h5 class="picto-txt" >Send it to your friend!</h5>
      <p class="picto-txt" >Finalize your Moobox and send it to all of your friends and family!</p>
    </div>
  </div>
<%

=begin  %>
  <div class="container container-features">
    <div class="row row-features">
      <div class="features col-sm-4 flex-column text-center">
        <%= image_tag 'bear-2.svg', class: 'picto animal-picto' %>
        <h5 class="picto-txt" >Choose your animal</h5>
        <p class="picto-txt" >Choose among our selection of animals and pick your favorite!</p>
      </div>

      <div class="features col-sm-4 flex-column text-center">
        <%= image_tag 'bell-53.svg', class: 'picto bell-picto' %>
        <h5 class="picto-txt" >Choose your sound</h5>
        <p class="picto-txt" >Select the best sound for your animal</p>
      </div>

      <div class="features col-sm-4 flex-column text-center">
        <%= image_tag 'send-2.svg', class: 'picto send-picto' %>
        <h5 class="picto-txt" >Send it to your friend!</h5>
        <p class="picto-txt" >Finalize your Moobox and send it to all of your friends and family!</p>
      </div>

    </div>
  </div>
<%
=end  %>
<!--   <hr class="mt-5 mb-5"> -->

  <div class="about">
    <div class="about-infos">
      <h1 class="about-title">Who are we?</h1>
      <p class="about-txt">Hello hello ! We are two web developers that want to practice a bit our Ruby on Rails skills so we created Moobox! We really hope you enjoy our super stupid but awesome app, please feel free to navigate and find your perfect Moobox and send it to your friends and family !</p>
      <p>Cheers,</p>
      <p>Paul & Mylene 🐮</p>
    </div>
    <%= image_tag 'about_moobox.png', class: 'about-img' %>
  </div>

  <div class="create">
    <%= image_tag 'moobox.png', class: 'create-img' %>
    <div class="create-infos">
      <h1 class="create-title">Be creative!</h1>
      <p class="create-txt">Let's get creative and create your own Moobox! Choose all of the components you need, from the right pattern to the right animal and sound, and BOOM! There's your Moobox!</p>
      <%= link_to 'Create your Moobox now!', new_box_path, class: 'btn-create mt-5'  %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav>
<!-- navbar top -->
  <div class="navbar-top">
    <div class="navbar-logo">
      <div class="home"> <%= link_to image_tag("logo_moobox_light.png"), root_path %> </div>
    </div>
  </div>

<%
=begin  %>

    <!-- Theme switch -->
    <div class="theme-items">
      <%= link_to "", root_path(theme: "#{ current_opposite_theme }"), id: "theme-link" %>
      <i class="<%= theme_is_dark? ? 'fas' : 'far' %> fa-moon"></i>
        <% if cookies[:theme] == "dark" %>
          <input id="theme-toggle" type="checkbox" class="toggle-theme" checked>
        <% else %>
          <input id="theme-toggle" type="checkbox" class="toggle-theme">
        <% end %>
      <i class="<%= theme_is_dark? ? 'far' : 'fas' %> fa-moon"></i>
    </div>
    <!-- Theme switch end -->
<%
=end  %>

<div class="navbar-bottom">
  <div class="container nav-bottom">
    <div class="row nav-bottom">
      <div class="col-lg-2 text-center nav-links">
        <%= link_to "Mooboxes", boxes_path %>
      </div>
      <div class="col-lg-2 text-center nav-links">
        <%= link_to "Create a Moobox", new_box_path %>
      </div>
      <div class="col-lg-2 text-center nav-links">
        <%= link_to "Sounds", sounds_path %>
      </div>
      <div class="col-lg-2 text-center nav-links">
        <%= link_to "Create a sound", new_sound_path %>
      </div>
      <div class="col-lg-2 text-center nav-links">
        <%= link_to "Styles", styles_path %>
      </div>
      <div class="col-lg-2 text-center nav-links">
        <%= link_to "Create a style", new_style_path %>
      </div>


    </div>
  </div>

</div>

<%
=begin  %>
<!-- navbar bottom -->
  <div class="navbar-bottom">
    <!-- navbar buttons -->
    <ul>
      <li> <%= link_to "Mooboxes", boxes_path %> </li>
      <li> <%= link_to "Create a Moobox", new_box_path %> </li>
      <li> <%= link_to "Sounds", sounds_path %> </li>
      <li> <%= link_to "Create a sound", new_sound_path %> </li>
      <li> <%= link_to "Styles", styles_path %> </li>
      <li> <%= link_to "Create a style", new_style_path %> </li>
      <% if user_signed_in? %>
        <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li> <%= link_to "Log in", new_user_session_path %> </li>
        <li> <%= link_to "Sign in", new_user_registration_path %> </li>
      <% end %>
    </ul>
  </div>

<%
=end  %>

</nav>

app/views/sounds/_play_button.html.erb
<% if sound.sound_file.attached? %>
  <button class="play-btns btn btn-primary" id="play-<%= id %>" data-id="<%= id %>">Play</button>

    <!-- SOUND TAG -->
    <%=
      cl_video_tag sound.sound_file.key,
      controls: true,
      height: '20px',
      width: '300px',
      poster: false,
      disablePictureInPicture: true,
      playsinline: true,
      id: "sound-#{id}",
      class: "sound-bars",
      'data-id': id
    %>
    <!-- SOUND TAG -->

<% end %>

app/views/sounds/edit.html.erb
<h1>Sounds#edit</h1>
<p>Find me in app/views/sounds/edit.html.erb</p>

<%= simple_form_for @sound do |f| %>
  <%= f.input :name, placeholder: "Name" %>
  <%= f.input :sound_file, as: :file %>
  <%= f.submit "Moo!" %>
<% end %>

app/views/sounds/index.html.erb
<h1>Sounds#index</h1>
<p>Find me in app/views/sounds/index.html.erb</p>

<ul>
  <% @sounds.each_with_index do |sound, i| %>
    <li>
      <%= sound.name %>
      <%= render 'play_button', sound: sound, id: i %> | <%= link_to "Edit", edit_sound_path(sound) %> | <%= link_to "Delete", sound_path(sound), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/sounds/new.html.erb
<h1>Sounds#new</h1>
<p>Find me in app/views/sounds/new.html.erb</p>

<%= simple_form_for @sound do |f| %>
  <%= f.input :name, placeholder: "Name" %>
  <%= f.input :sound_file, as: :file %>
  <%= f.submit "Moo!" %>
<% end %>

app/views/styles/edit.html.erb
<h1>Styles#edit</h1>
<p>Find me in app/views/styles/edit.html.erb</p>

<%= simple_form_for @style do |f| -%>
  <%= f.input :name, label: false, placeholder: "Name" %>
  <%= f.input :pattern, as: :file %>
  <%= f.submit "Submit modifications" %>
<% end -%>

app/views/styles/index.html.erb
<h1>Styles#index</h1>
<p>Find me in app/views/styles/index.html.erb</p>

<ul>
  <% @styles.each_with_index do |style, i| %>
    <li>
      <%= style.name %> | <%= link_to "Edit style", edit_style_path(style) %> | <%= link_to "Delete style", style_path(style), method: :delete %>
      <%= cl_image_tag style.pattern.key, height: '170px', width: '300px', alt: "alttext" %>
    </li>
  <% end %>
</ul>

app/views/styles/new.html.erb
<h1>Styles#new</h1>
<p>Find me in app/views/styles/new.html.erb</p>


<%= simple_form_for @style do |f| -%>
  <%= f.input :name, label: false, placeholder: "Name" %>
  <%= f.input :pattern, as: :file %>
  <%= f.submit "Submit new style" %>
<% end -%>